language: java
jdk:
  - oraclejdk8

install: ./gradlew setupCIWorkspace -S
script: ./gradlew build

# use container to speed up builds
sudo: false

env:
  global:
    TERM=dumb

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native/